### ISSUE TITLE
TypeError: first argument must be callable or None

### ISSUE THREAD

**Issue by AlienKevin** [sjunhongshen/Tag-LLM#6]
I got the following error during training:
```
Error executing job with overrides: []
Traceback (most recent call last):
  File "/Users/kevin/Tag-LLM/src/train.py", line 376, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/Users/kevin/miniconda3/envs/tagllm/lib/python3.8/site-packages/transformers/trainer.py", line 1633, in train
    return inner_training_loop(
  File "/Users/kevin/miniconda3/envs/tagllm/lib/python3.8/site-packages/transformers/trainer.py", line 1902, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/Users/kevin/miniconda3/envs/tagllm/lib/python3.8/site-packages/transformers/trainer.py", line 2638, in training_step
    inputs = self._prepare_inputs(inputs)
  File "/Users/kevin/miniconda3/envs/tagllm/lib/python3.8/site-packages/transformers/trainer.py", line 2583, in _prepare_inputs
    inputs = self._prepare_input(inputs)
  File "/Users/kevin/miniconda3/envs/tagllm/lib/python3.8/site-packages/transformers/trainer.py", line 2565, in _prepare_input
    return type(data)({k: self._prepare_input(v) for k, v in data.items()})
TypeError: first argument must be callable or None
```

The error was triggered in `transformers/trainer.py` when `type(data)` tries to get the type of data which is a defaultdict and reconstruct a new defaultdict after mapping its values using `_prepare_input`. However, the `defaultdict` constructor cannot be used this way:
```
def _prepare_input(self, data: Union[torch.Tensor, Any]) -> Union[torch.Tensor, Any]:
        """
        Prepares one `data` before feeding it to the model, be it a tensor or a nested list/dictionary of tensors.
        """
        if isinstance(data, Mapping):
            return type(data)({k: self._prepare_input(v) for k, v in data.items()})
        elif isinstance(data, (tuple, list)):
```

A fix is to convert the defaultdict to a dict at the end of the `DataCollatorForTagLLM` in `collator.py`:
```
...
        if len(reg_idx) > 0:
            model_inputs["reg_idx"] = reg_idx
            model_inputs["reg_dim"] = reg_dim
            model_inputs["reg_pred_idx"] = reg_pred_idx
        if len(clf_idx) > 0:
            model_inputs["clf_idx"] = clf_idx
    
        return dict(model_inputs)
```

**Comment by AlienKevin** [comment]
Conda environment used (copied from requirements.txt):
```
name: tagllm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy=1.21.2
  - pandas=1.5.3
  - pydantic=1.10.12
  - pip:
    - accelerate==0.23.0
    - datasets==2.17.1
    - deepspeed==0.8.3
    - evaluate==0.3.0
    - fire==0.5.0
    - hydra-core==1.2.0
    - omegaconf>=2.1.1
    - openai==0.27.2
    - rouge_score==0.1.2
    - nltk==3.6.2
    - sentencepiece==0.1.98
    - torch==2.0.0
    - wandb==0.13.4
    - PyTDC==0.4.1
    - peptides==0.3.2
    - peft==0.5.0
    - git+https://github.com/huggingface/transformers@fb366b9a
```

**Comment by sjunhongshen** [comment]
Thanks! Fixed in Mar 29 commit.
